# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import quote_pb2 as quote__pb2


class QuoteServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListQuoteHistory = channel.unary_unary(
        '/stockbuddy.QuoteService/ListQuoteHistory',
        request_serializer=quote__pb2.QuoteRequest.SerializeToString,
        response_deserializer=quote__pb2.QuoteResponse.FromString,
        )


class QuoteServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListQuoteHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuoteServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListQuoteHistory': grpc.unary_unary_rpc_method_handler(
          servicer.ListQuoteHistory,
          request_deserializer=quote__pb2.QuoteRequest.FromString,
          response_serializer=quote__pb2.QuoteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stockbuddy.QuoteService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
