# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quote_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quote_service.proto',
  package='stockbuddy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13quote_service.proto\x12\nstockbuddy\"\x85\x01\n\x05Quote\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04open\x18\x02 \x01(\x02\x12\x0c\n\x04high\x18\x03 \x01(\x02\x12\x0b\n\x03low\x18\x04 \x01(\x02\x12\r\n\x05\x63lose\x18\x05 \x01(\x02\x12\x11\n\tadj_close\x18\x06 \x01(\x02\x12\x0e\n\x06volume\x18\x07 \x01(\x05\x12\x11\n\ttimestamp\x18\x08 \x01(\x05\".\n\x0cQuoteRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\x05\"2\n\rQuoteResponse\x12!\n\x06quotes\x18\x01 \x03(\x0b\x32\x11.stockbuddy.Quote2W\n\x0cQuoteService\x12G\n\x10ListQuoteHistory\x12\x18.stockbuddy.QuoteRequest\x1a\x19.stockbuddy.QuoteResponseb\x06proto3')
)




_QUOTE = _descriptor.Descriptor(
  name='Quote',
  full_name='stockbuddy.Quote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='stockbuddy.Quote.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='stockbuddy.Quote.open', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='stockbuddy.Quote.high', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='stockbuddy.Quote.low', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='stockbuddy.Quote.close', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='adj_close', full_name='stockbuddy.Quote.adj_close', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='stockbuddy.Quote.volume', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='stockbuddy.Quote.timestamp', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=169,
)


_QUOTEREQUEST = _descriptor.Descriptor(
  name='QuoteRequest',
  full_name='stockbuddy.QuoteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='stockbuddy.QuoteRequest.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='stockbuddy.QuoteRequest.period', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=217,
)


_QUOTERESPONSE = _descriptor.Descriptor(
  name='QuoteResponse',
  full_name='stockbuddy.QuoteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quotes', full_name='stockbuddy.QuoteResponse.quotes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=269,
)

_QUOTERESPONSE.fields_by_name['quotes'].message_type = _QUOTE
DESCRIPTOR.message_types_by_name['Quote'] = _QUOTE
DESCRIPTOR.message_types_by_name['QuoteRequest'] = _QUOTEREQUEST
DESCRIPTOR.message_types_by_name['QuoteResponse'] = _QUOTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Quote = _reflection.GeneratedProtocolMessageType('Quote', (_message.Message,), {
  'DESCRIPTOR' : _QUOTE,
  '__module__' : 'quote_service_pb2'
  # @@protoc_insertion_point(class_scope:stockbuddy.Quote)
  })
_sym_db.RegisterMessage(Quote)

QuoteRequest = _reflection.GeneratedProtocolMessageType('QuoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUOTEREQUEST,
  '__module__' : 'quote_service_pb2'
  # @@protoc_insertion_point(class_scope:stockbuddy.QuoteRequest)
  })
_sym_db.RegisterMessage(QuoteRequest)

QuoteResponse = _reflection.GeneratedProtocolMessageType('QuoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUOTERESPONSE,
  '__module__' : 'quote_service_pb2'
  # @@protoc_insertion_point(class_scope:stockbuddy.QuoteResponse)
  })
_sym_db.RegisterMessage(QuoteResponse)



_QUOTESERVICE = _descriptor.ServiceDescriptor(
  name='QuoteService',
  full_name='stockbuddy.QuoteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=271,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListQuoteHistory',
    full_name='stockbuddy.QuoteService.ListQuoteHistory',
    index=0,
    containing_service=None,
    input_type=_QUOTEREQUEST,
    output_type=_QUOTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUOTESERVICE)

DESCRIPTOR.services_by_name['QuoteService'] = _QUOTESERVICE

# @@protoc_insertion_point(module_scope)
