load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
  name = "fileio",
  srcs = ["readlines.go"],
  importpath = "stockbuddy/fileio",
)
