load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "yahoo_finance_client",
    srcs = ["yahoo_finance_client.go"],
    importpath = "stockbuddy/quote_service/yahoofinance",
    visibility = ["//visibility:public"],
)
